/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package login;

/**
 *
 * @author julia
 */
public class Sistema extends javax.swing.JFrame {

    public Sistema() {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelCarros = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PanelEmpleados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelClientes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PanelPlanilla = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PanelProducto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelFactura = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PanelSorteo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        IconCarro = new javax.swing.JLabel();
        btnCarro = new javax.swing.JPanel();
        IconTrabajador = new javax.swing.JLabel();
        btntrabajador = new javax.swing.JPanel();
        IconCliente = new javax.swing.JLabel();
        btncliente = new javax.swing.JPanel();
        IconPlantilla = new javax.swing.JLabel();
        btnPlantilla = new javax.swing.JPanel();
        iconproducto = new javax.swing.JLabel();
        btnproducto = new javax.swing.JPanel();
        Iconfactura = new javax.swing.JLabel();
        btnfactura = new javax.swing.JPanel();
        btncerrarsesion = new javax.swing.JPanel();
        txtcerrarsesion = new javax.swing.JLabel();
        BackGr0undlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelCarros.setBackground(new java.awt.Color(255, 255, 255));
        PanelCarros.setForeground(new java.awt.Color(255, 0, 0));
        PanelCarros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("COCHES");
        PanelCarros.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        jTabbedPane1.addTab("tab1", PanelCarros);

        PanelEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        PanelEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("EMPLEADOS");
        PanelEmpleados.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 280, 80));

        jTabbedPane1.addTab("tab2", PanelEmpleados);

        PanelClientes.setBackground(new java.awt.Color(255, 255, 255));
        PanelClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("CLIENTES");
        PanelClientes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 230, 80));

        jTabbedPane1.addTab("tab3", PanelClientes);

        PanelPlanilla.setBackground(new java.awt.Color(255, 255, 255));
        PanelPlanilla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("PLANILLA");
        PanelPlanilla.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 240, 80));

        jTabbedPane1.addTab("tab4", PanelPlanilla);

        PanelProducto.setBackground(new java.awt.Color(255, 255, 255));
        PanelProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelProductoMouseClicked(evt);
            }
        });
        PanelProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("PRODUCTO");
        PanelProducto.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 270, 80));

        jTabbedPane1.addTab("tab5", PanelProducto);

        PanelFactura.setBackground(new java.awt.Color(255, 255, 255));
        PanelFactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("FACTURA");
        PanelFactura.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 240, 80));

        jTabbedPane1.addTab("tab6", PanelFactura);

        PanelSorteo.setBackground(new java.awt.Color(255, 255, 255));
        PanelSorteo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("SORTEO");
        PanelSorteo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 240, 80));

        jTabbedPane1.addTab("tab7", PanelSorteo);

        Background.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1120, 720));

        IconCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/CarroIcon.png"))); // NOI18N
        IconCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconCarroMouseClicked(evt);
            }
        });
        Background.add(IconCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnCarro.setBackground(new java.awt.Color(153, 0, 0));
        btnCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCarroLayout = new javax.swing.GroupLayout(btnCarro);
        btnCarro.setLayout(btnCarroLayout);
        btnCarroLayout.setHorizontalGroup(
            btnCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        btnCarroLayout.setVerticalGroup(
            btnCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Background.add(btnCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 70));

        IconTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/TrabajadorIcon.png"))); // NOI18N
        IconTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconTrabajadorMouseClicked(evt);
            }
        });
        Background.add(IconTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        btntrabajador.setBackground(new java.awt.Color(153, 0, 0));
        btntrabajador.setForeground(new java.awt.Color(153, 0, 0));
        btntrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntrabajadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btntrabajadorLayout = new javax.swing.GroupLayout(btntrabajador);
        btntrabajador.setLayout(btntrabajadorLayout);
        btntrabajadorLayout.setHorizontalGroup(
            btntrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        btntrabajadorLayout.setVerticalGroup(
            btntrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Background.add(btntrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 70));

        IconCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Cliente2Icon.png"))); // NOI18N
        IconCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconClienteMouseClicked(evt);
            }
        });
        Background.add(IconCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 60, 80));

        btncliente.setBackground(new java.awt.Color(153, 0, 0));
        btncliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnclienteLayout = new javax.swing.GroupLayout(btncliente);
        btncliente.setLayout(btnclienteLayout);
        btnclienteLayout.setHorizontalGroup(
            btnclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        btnclienteLayout.setVerticalGroup(
            btnclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Background.add(btncliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 70));

        IconPlantilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/PlantillaIcon.png"))); // NOI18N
        IconPlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconPlantillaMouseClicked(evt);
            }
        });
        Background.add(IconPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 60, 80));

        btnPlantilla.setBackground(new java.awt.Color(153, 0, 0));
        btnPlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlantillaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnPlantillaLayout = new javax.swing.GroupLayout(btnPlantilla);
        btnPlantilla.setLayout(btnPlantillaLayout);
        btnPlantillaLayout.setHorizontalGroup(
            btnPlantillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        btnPlantillaLayout.setVerticalGroup(
            btnPlantillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        Background.add(btnPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 80));

        iconproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/ProductoIcon.png"))); // NOI18N
        Background.add(iconproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 60, 80));

        btnproducto.setBackground(new java.awt.Color(153, 0, 0));
        btnproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnproductoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnproductoLayout = new javax.swing.GroupLayout(btnproducto);
        btnproducto.setLayout(btnproductoLayout);
        btnproductoLayout.setHorizontalGroup(
            btnproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        btnproductoLayout.setVerticalGroup(
            btnproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        Background.add(btnproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, 80));

        Iconfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/FacturaIcon.png"))); // NOI18N
        Background.add(Iconfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 50, 60));

        btnfactura.setBackground(new java.awt.Color(153, 0, 0));
        btnfactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfacturaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnfacturaLayout = new javax.swing.GroupLayout(btnfactura);
        btnfactura.setLayout(btnfacturaLayout);
        btnfacturaLayout.setHorizontalGroup(
            btnfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        btnfacturaLayout.setVerticalGroup(
            btnfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        Background.add(btnfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, 80));

        btncerrarsesion.setBackground(new java.awt.Color(255, 255, 255));
        btncerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarsesionMouseClicked(evt);
            }
        });

        txtcerrarsesion.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtcerrarsesion.setForeground(new java.awt.Color(0, 0, 0));
        txtcerrarsesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtcerrarsesion.setText("CERRAR SESIÓN");
        txtcerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcerrarsesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btncerrarsesionLayout = new javax.swing.GroupLayout(btncerrarsesion);
        btncerrarsesion.setLayout(btncerrarsesionLayout);
        btncerrarsesionLayout.setHorizontalGroup(
            btncerrarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtcerrarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btncerrarsesionLayout.setVerticalGroup(
            btncerrarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btncerrarsesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtcerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Background.add(btncerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 110, 40));

        BackGr0undlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Sistema.jpg"))); // NOI18N
        BackGr0undlbl.setText("jLabel1");
        Background.add(BackGr0undlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IconCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconCarroMouseClicked
      jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_IconCarroMouseClicked

    private void IconTrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconTrabajadorMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_IconTrabajadorMouseClicked

    private void IconClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconClienteMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_IconClienteMouseClicked

    private void txtcerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcerrarsesionMouseClicked
        login form= new login();
            form.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_txtcerrarsesionMouseClicked

    private void btnCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarroMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnCarroMouseClicked

    private void btntrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntrabajadorMouseClicked
        jTabbedPane1.setSelectedIndex(1);        
    }//GEN-LAST:event_btntrabajadorMouseClicked

    private void btnclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclienteMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnclienteMouseClicked
        
    private void btnfacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfacturaMouseClicked
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_btnfacturaMouseClicked

    private void IconPlantillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconPlantillaMouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_IconPlantillaMouseClicked

    private void btnPlantillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlantillaMouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnPlantillaMouseClicked

    
    private void btnproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproductoMouseClicked
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnproductoMouseClicked

    private void PanelProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelProductoMouseClicked
        
    }//GEN-LAST:event_PanelProductoMouseClicked

    private void btncerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarsesionMouseClicked
        login form= new login();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncerrarsesionMouseClicked

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGr0undlbl;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel IconCarro;
    private javax.swing.JLabel IconCliente;
    private javax.swing.JLabel IconPlantilla;
    private javax.swing.JLabel IconTrabajador;
    private javax.swing.JLabel Iconfactura;
    private javax.swing.JPanel PanelCarros;
    private javax.swing.JPanel PanelClientes;
    private javax.swing.JPanel PanelEmpleados;
    private javax.swing.JPanel PanelFactura;
    private javax.swing.JPanel PanelPlanilla;
    private javax.swing.JPanel PanelProducto;
    private javax.swing.JPanel PanelSorteo;
    private javax.swing.JPanel btnCarro;
    private javax.swing.JPanel btnPlantilla;
    private javax.swing.JPanel btncerrarsesion;
    private javax.swing.JPanel btncliente;
    private javax.swing.JPanel btnfactura;
    private javax.swing.JPanel btnproducto;
    private javax.swing.JPanel btntrabajador;
    private javax.swing.JLabel iconproducto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel txtcerrarsesion;
    // End of variables declaration//GEN-END:variables

}
