/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package login;

import sql.crudsql;

/**
 *
 * @author julia
 */
public class Sistema extends javax.swing.JFrame {

    public Sistema() {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        TabbedPaneMain = new javax.swing.JTabbedPane();
        PanelCarros = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        lblregistrarcoches = new javax.swing.JLabel();
        lblcoche = new javax.swing.JLabel();
        txtplavehiculo = new javax.swing.JTextField();
        lblcoche1 = new javax.swing.JLabel();
        txttipvehiculo = new javax.swing.JTextField();
        lblcoche2 = new javax.swing.JLabel();
        txtmodvehiculo = new javax.swing.JTextField();
        lblcoche3 = new javax.swing.JLabel();
        txtcolvehiculo = new javax.swing.JTextField();
        lblcoche4 = new javax.swing.JLabel();
        txtmarvehiculo = new javax.swing.JTextField();
        lblcoche6 = new javax.swing.JLabel();
        txtcedcliente = new javax.swing.JTextField();
        lblcoche5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtobsvehiculo = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        fondopiratacoche = new javax.swing.JLabel();
        PanelEmpleados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbcedempleado = new javax.swing.JLabel();
        lbnomempleado = new javax.swing.JLabel();
        lbapeempleado = new javax.swing.JLabel();
        lbdirempleado = new javax.swing.JLabel();
        lbtelempleado = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        lblciuempleado = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtsulempleado = new javax.swing.JTextField();
        txtnomempleado = new javax.swing.JTextField();
        txtcedempleado1 = new javax.swing.JTextField();
        txtapeempleado = new javax.swing.JTextField();
        txtdirempleado = new javax.swing.JTextField();
        txttelempleado = new javax.swing.JTextField();
        txtmailempleado = new javax.swing.JTextField();
        txtciuempleado = new javax.swing.JTextField();
        txtfecempleado = new javax.swing.JTextField();
        txtingempleado7 = new javax.swing.JTextField();
        txtespempleado = new javax.swing.JTextField();
        btnregempleado = new javax.swing.JButton();
        PanelClientes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        PanelPlanilla = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbingplanilla = new javax.swing.JLabel();
        lbsalplanilla = new javax.swing.JLabel();
        lblnomcliplanilla = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbtipvehplanilla = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtsalplanilla = new javax.swing.JTextField();
        txtingplanilla = new javax.swing.JTextField();
        txtsalplanilla1 = new javax.swing.JTextField();
        txtnomcliplanilla = new javax.swing.JTextField();
        txtplavehplanilla = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        cmbtiopvehicul = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtempleadoslist = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtdesplanilla = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtobsplanilla = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        PanelProducto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbcodproducto = new javax.swing.JLabel();
        lbfecproducto = new javax.swing.JLabel();
        lbnomproducto = new javax.swing.JLabel();
        lbcatproducto = new javax.swing.JLabel();
        lblcomproducto = new javax.swing.JLabel();
        lbvenproducto = new javax.swing.JLabel();
        lbstock = new javax.swing.JLabel();
        txtnomproducto = new javax.swing.JTextField();
        cbxcatproducto = new javax.swing.JComboBox<>();
        txtstoproducto = new javax.swing.JTextField();
        txtfecproducto1 = new javax.swing.JTextField();
        txtcodproducto2 = new javax.swing.JTextField();
        txtcomproducto = new javax.swing.JTextField();
        txtvenproducto = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        PanelFactura = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PanelSorteo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        IconCarro = new javax.swing.JLabel();
        btnCarro = new javax.swing.JPanel();
        IconTrabajador = new javax.swing.JLabel();
        btntrabajador = new javax.swing.JPanel();
        IconCliente = new javax.swing.JLabel();
        btncliente = new javax.swing.JPanel();
        IconPlantilla = new javax.swing.JLabel();
        btnPlantilla = new javax.swing.JPanel();
        iconproducto = new javax.swing.JLabel();
        btnproducto = new javax.swing.JPanel();
        Iconfactura = new javax.swing.JLabel();
        btnfactura = new javax.swing.JPanel();
        btncerrarsesion = new javax.swing.JPanel();
        txtcerrarsesion = new javax.swing.JLabel();
        BackGr0undlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelCarros.setBackground(new java.awt.Color(255, 255, 255));
        PanelCarros.setForeground(new java.awt.Color(255, 0, 0));
        PanelCarros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setText("jButton2");
        PanelCarros.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));

        lblregistrarcoches.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblregistrarcoches.setForeground(new java.awt.Color(102, 102, 102));
        lblregistrarcoches.setText("REGISTRAR VEHICULOS");
        PanelCarros.add(lblregistrarcoches, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblcoche.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblcoche.setText("Placa del Vehículo:");
        PanelCarros.add(lblcoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txtplavehiculo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtplavehiculo.setForeground(new java.awt.Color(51, 51, 51));
        txtplavehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtplavehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplavehiculoActionPerformed(evt);
            }
        });
        PanelCarros.add(txtplavehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 200, -1));

        lblcoche1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblcoche1.setText("Tipo de Vehículo:");
        PanelCarros.add(lblcoche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        txttipvehiculo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txttipvehiculo.setForeground(new java.awt.Color(51, 51, 51));
        txttipvehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelCarros.add(txttipvehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 200, -1));

        lblcoche2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblcoche2.setText("Modelo de Vehículo:");
        PanelCarros.add(lblcoche2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        txtmodvehiculo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtmodvehiculo.setForeground(new java.awt.Color(51, 51, 51));
        txtmodvehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmodvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodvehiculoActionPerformed(evt);
            }
        });
        PanelCarros.add(txtmodvehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 200, -1));

        lblcoche3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblcoche3.setText("Color del Vehículo:");
        PanelCarros.add(lblcoche3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        txtcolvehiculo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtcolvehiculo.setForeground(new java.awt.Color(51, 51, 51));
        txtcolvehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelCarros.add(txtcolvehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 200, -1));

        lblcoche4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblcoche4.setText("Marca del Vehículo:");
        PanelCarros.add(lblcoche4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        txtmarvehiculo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtmarvehiculo.setForeground(new java.awt.Color(51, 51, 51));
        txtmarvehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelCarros.add(txtmarvehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 200, -1));

        lblcoche6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblcoche6.setText("Cedula del propietario:");
        PanelCarros.add(lblcoche6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        txtcedcliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtcedcliente.setForeground(new java.awt.Color(51, 51, 51));
        txtcedcliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelCarros.add(txtcedcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 200, -1));

        lblcoche5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblcoche5.setText("Observaciónes:");
        PanelCarros.add(lblcoche5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        jPasswordField1.setText("jPasswordField1");
        PanelCarros.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        txtobsvehiculo.setColumns(20);
        txtobsvehiculo.setForeground(new java.awt.Color(51, 51, 51));
        txtobsvehiculo.setRows(5);
        txtobsvehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtobsvehiculo);

        PanelCarros.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        jButton1.setBackground(new java.awt.Color(154, 0, 0));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGISTRAR VEHICULO");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(154, 0, 0), 0));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        PanelCarros.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 160, 40));

        fondopiratacoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/FondoPirata.jpg"))); // NOI18N
        PanelCarros.add(fondopiratacoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, -1));

        TabbedPaneMain.addTab("tab1", PanelCarros);

        PanelEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        PanelEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("REGISTRO EMPLEADOS");
        PanelEmpleados.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 540, 80));

        lbcedempleado.setText("Cedula:");
        PanelEmpleados.add(lbcedempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 60, 20));

        lbnomempleado.setText("Nombre:");
        PanelEmpleados.add(lbnomempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        lbapeempleado.setText("Apellido:");
        PanelEmpleados.add(lbapeempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        lbdirempleado.setText("Dirección:");
        PanelEmpleados.add(lbdirempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        lbtelempleado.setText("Telefono:");
        PanelEmpleados.add(lbtelempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        lbemail.setText("Email:");
        PanelEmpleados.add(lbemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        lblciuempleado.setText("Ciudad:");
        PanelEmpleados.add(lblciuempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, -1));

        jLabel15.setText("Fecha Nacimiento:");
        PanelEmpleados.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, -1));

        jLabel16.setText("Fecha Ingreso:");
        PanelEmpleados.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, 20));

        jLabel17.setText("Especialidad:");
        PanelEmpleados.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        jLabel18.setText("Sueldo:");
        PanelEmpleados.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        txtsulempleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtsulempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsulempleadoActionPerformed(evt);
            }
        });
        PanelEmpleados.add(txtsulempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 200, 30));

        txtnomempleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        PanelEmpleados.add(txtnomempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 200, 30));

        txtcedempleado1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtcedempleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedempleado1ActionPerformed(evt);
            }
        });
        PanelEmpleados.add(txtcedempleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 200, 30));

        txtapeempleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtapeempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapeempleadoActionPerformed(evt);
            }
        });
        PanelEmpleados.add(txtapeempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 200, 30));

        txtdirempleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtdirempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdirempleadoActionPerformed(evt);
            }
        });
        PanelEmpleados.add(txtdirempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 200, 30));

        txttelempleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txttelempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelempleadoActionPerformed(evt);
            }
        });
        PanelEmpleados.add(txttelempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 200, 30));

        txtmailempleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtmailempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailempleadoActionPerformed(evt);
            }
        });
        PanelEmpleados.add(txtmailempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 200, 30));

        txtciuempleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtciuempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtciuempleadoActionPerformed(evt);
            }
        });
        PanelEmpleados.add(txtciuempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 200, 30));

        txtfecempleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtfecempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfecempleadoActionPerformed(evt);
            }
        });
        PanelEmpleados.add(txtfecempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 200, 30));

        txtingempleado7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtingempleado7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtingempleado7ActionPerformed(evt);
            }
        });
        PanelEmpleados.add(txtingempleado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 200, 30));

        txtespempleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtespempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtespempleadoActionPerformed(evt);
            }
        });
        PanelEmpleados.add(txtespempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 200, 30));

        btnregempleado.setBackground(new java.awt.Color(51, 0, 0));
        btnregempleado.setForeground(new java.awt.Color(255, 255, 255));
        btnregempleado.setText("Registrar");
        btnregempleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnregempleado.setBorderPainted(false);
        btnregempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregempleadoActionPerformed(evt);
            }
        });
        PanelEmpleados.add(btnregempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 150, 50));

        TabbedPaneMain.addTab("tab2", PanelEmpleados);

        PanelClientes.setBackground(new java.awt.Color(255, 255, 255));
        PanelClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("CLIENTES");
        PanelClientes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 230, 80));

        jButton3.setText("eee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelClientes.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        TabbedPaneMain.addTab("tab3", PanelClientes);

        PanelPlanilla.setBackground(new java.awt.Color(255, 255, 255));
        PanelPlanilla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("REGISTRO PLANILLA");
        PanelPlanilla.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 480, 80));

        lbingplanilla.setText("Fecha Ingreso:");
        PanelPlanilla.add(lbingplanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        lbsalplanilla.setText("Fecha Salida:");
        PanelPlanilla.add(lbsalplanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, -1));

        lblnomcliplanilla.setText("Nombre Cliente:");
        PanelPlanilla.add(lblnomcliplanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 90, -1));

        jLabel10.setText("Placa Vehículo:");
        PanelPlanilla.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, -1));

        jLabel11.setText("Tipo de Trabajo:");
        PanelPlanilla.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, -1));

        lbtipvehplanilla.setText("Tipo de Vehículo:");
        PanelPlanilla.add(lbtipvehplanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jLabel13.setText("Nombre Empleado:");
        PanelPlanilla.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabel14.setText("Descripción:");
        PanelPlanilla.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        txtsalplanilla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        PanelPlanilla.add(txtsalplanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 200, 30));

        txtingplanilla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        PanelPlanilla.add(txtingplanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 200, 30));

        txtsalplanilla1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtsalplanilla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalplanilla1ActionPerformed(evt);
            }
        });
        PanelPlanilla.add(txtsalplanilla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 200, 30));

        txtnomcliplanilla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        PanelPlanilla.add(txtnomcliplanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 200, 30));

        txtplavehplanilla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        PanelPlanilla.add(txtplavehplanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 200, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mantenimiento", "Reparación" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelPlanilla.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 190, 30));

        cmbtiopvehicul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moto", "Automóvil", "Camioneta", "Camion" }));
        PanelPlanilla.add(cmbtiopvehicul, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 200, 30));

        txtempleadoslist.setEditable(false);
        txtempleadoslist.setColumns(20);
        txtempleadoslist.setRows(5);
        txtempleadoslist.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        jScrollPane2.setViewportView(txtempleadoslist);

        PanelPlanilla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 300, -1));

        jLabel1.setText("Observación:");
        PanelPlanilla.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, -1, -1));

        txtdesplanilla.setColumns(20);
        txtdesplanilla.setRows(5);
        txtdesplanilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        jScrollPane3.setViewportView(txtdesplanilla);

        PanelPlanilla.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 240, -1));

        txtobsplanilla.setColumns(20);
        txtobsplanilla.setRows(5);
        txtobsplanilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        jScrollPane4.setViewportView(txtobsplanilla);

        PanelPlanilla.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 240, -1));

        jButton5.setBackground(new java.awt.Color(51, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Registrar");
        PanelPlanilla.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 140, 50));

        TabbedPaneMain.addTab("tab4", PanelPlanilla);

        PanelProducto.setBackground(new java.awt.Color(255, 255, 255));
        PanelProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelProductoMouseClicked(evt);
            }
        });
        PanelProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("REGISTRO PRODUCTOS");
        PanelProducto.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 550, 80));

        lbcodproducto.setText("Código:");
        PanelProducto.add(lbcodproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        lbfecproducto.setText("Fecha:");
        PanelProducto.add(lbfecproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        lbnomproducto.setText("Nombre:");
        PanelProducto.add(lbnomproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 80, 20));

        lbcatproducto.setText("Categoria:");
        PanelProducto.add(lbcatproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        lblcomproducto.setText("Precio Compra:");
        PanelProducto.add(lblcomproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        lbvenproducto.setText("Precio Venta:");
        PanelProducto.add(lbvenproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        lbstock.setText("Stock:");
        PanelProducto.add(lbstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        txtnomproducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtnomproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomproductoActionPerformed(evt);
            }
        });
        PanelProducto.add(txtnomproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 200, 30));

        cbxcatproducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Repuesto", "Accesorio" }));
        PanelProducto.add(cbxcatproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 200, 30));

        txtstoproducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtstoproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstoproductoActionPerformed(evt);
            }
        });
        PanelProducto.add(txtstoproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 220, 30));

        txtfecproducto1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtfecproducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfecproducto1ActionPerformed(evt);
            }
        });
        PanelProducto.add(txtfecproducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 200, 30));

        txtcodproducto2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtcodproducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodproducto2ActionPerformed(evt);
            }
        });
        PanelProducto.add(txtcodproducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 200, 30));

        txtcomproducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtcomproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcomproductoActionPerformed(evt);
            }
        });
        PanelProducto.add(txtcomproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 220, 30));

        txtvenproducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        txtvenproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvenproductoActionPerformed(evt);
            }
        });
        PanelProducto.add(txtvenproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 220, 30));

        jButton6.setBackground(new java.awt.Color(51, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Registrar");
        PanelProducto.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 150, 40));

        TabbedPaneMain.addTab("tab5", PanelProducto);

        PanelFactura.setBackground(new java.awt.Color(255, 255, 255));
        PanelFactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("FACTURA");
        PanelFactura.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 240, 80));

        TabbedPaneMain.addTab("tab6", PanelFactura);

        PanelSorteo.setBackground(new java.awt.Color(255, 255, 255));
        PanelSorteo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("SORTEO");
        PanelSorteo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 240, 80));

        TabbedPaneMain.addTab("tab7", PanelSorteo);

        Background.add(TabbedPaneMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1120, 720));

        IconCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/CarroIcon.png"))); // NOI18N
        IconCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconCarroMouseClicked(evt);
            }
        });
        Background.add(IconCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnCarro.setBackground(new java.awt.Color(153, 0, 0));
        btnCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCarroLayout = new javax.swing.GroupLayout(btnCarro);
        btnCarro.setLayout(btnCarroLayout);
        btnCarroLayout.setHorizontalGroup(
            btnCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        btnCarroLayout.setVerticalGroup(
            btnCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Background.add(btnCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 70));

        IconTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/TrabajadorIcon.png"))); // NOI18N
        IconTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconTrabajadorMouseClicked(evt);
            }
        });
        Background.add(IconTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        btntrabajador.setBackground(new java.awt.Color(153, 0, 0));
        btntrabajador.setForeground(new java.awt.Color(153, 0, 0));
        btntrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntrabajadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btntrabajadorLayout = new javax.swing.GroupLayout(btntrabajador);
        btntrabajador.setLayout(btntrabajadorLayout);
        btntrabajadorLayout.setHorizontalGroup(
            btntrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        btntrabajadorLayout.setVerticalGroup(
            btntrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Background.add(btntrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 70));

        IconCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Cliente2Icon.png"))); // NOI18N
        IconCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconClienteMouseClicked(evt);
            }
        });
        Background.add(IconCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 60, 80));

        btncliente.setBackground(new java.awt.Color(153, 0, 0));
        btncliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnclienteLayout = new javax.swing.GroupLayout(btncliente);
        btncliente.setLayout(btnclienteLayout);
        btnclienteLayout.setHorizontalGroup(
            btnclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        btnclienteLayout.setVerticalGroup(
            btnclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Background.add(btncliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 70));

        IconPlantilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/PlantillaIcon.png"))); // NOI18N
        IconPlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconPlantillaMouseClicked(evt);
            }
        });
        Background.add(IconPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 60, 80));

        btnPlantilla.setBackground(new java.awt.Color(153, 0, 0));
        btnPlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlantillaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnPlantillaLayout = new javax.swing.GroupLayout(btnPlantilla);
        btnPlantilla.setLayout(btnPlantillaLayout);
        btnPlantillaLayout.setHorizontalGroup(
            btnPlantillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        btnPlantillaLayout.setVerticalGroup(
            btnPlantillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        Background.add(btnPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 80));

        iconproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/ProductoIcon.png"))); // NOI18N
        Background.add(iconproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 60, 80));

        btnproducto.setBackground(new java.awt.Color(153, 0, 0));
        btnproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnproductoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnproductoLayout = new javax.swing.GroupLayout(btnproducto);
        btnproducto.setLayout(btnproductoLayout);
        btnproductoLayout.setHorizontalGroup(
            btnproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        btnproductoLayout.setVerticalGroup(
            btnproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        Background.add(btnproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, 80));

        Iconfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/FacturaIcon.png"))); // NOI18N
        Background.add(Iconfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 50, 60));

        btnfactura.setBackground(new java.awt.Color(153, 0, 0));
        btnfactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfacturaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnfacturaLayout = new javax.swing.GroupLayout(btnfactura);
        btnfactura.setLayout(btnfacturaLayout);
        btnfacturaLayout.setHorizontalGroup(
            btnfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        btnfacturaLayout.setVerticalGroup(
            btnfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        Background.add(btnfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, 80));

        btncerrarsesion.setBackground(new java.awt.Color(255, 255, 255));
        btncerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarsesionMouseClicked(evt);
            }
        });

        txtcerrarsesion.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtcerrarsesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtcerrarsesion.setText("CERRAR SESIÓN");
        txtcerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcerrarsesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btncerrarsesionLayout = new javax.swing.GroupLayout(btncerrarsesion);
        btncerrarsesion.setLayout(btncerrarsesionLayout);
        btncerrarsesionLayout.setHorizontalGroup(
            btncerrarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtcerrarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btncerrarsesionLayout.setVerticalGroup(
            btncerrarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btncerrarsesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtcerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Background.add(btncerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 110, 40));

        BackGr0undlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Sistema.jpg"))); // NOI18N
        BackGr0undlbl.setText("jLabel1");
        Background.add(BackGr0undlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    crudsql objcrud=new crudsql();
    private void IconCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconCarroMouseClicked
      TabbedPaneMain.setSelectedIndex(0);
    }//GEN-LAST:event_IconCarroMouseClicked

    private void IconTrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconTrabajadorMouseClicked
        TabbedPaneMain.setSelectedIndex(1);
    }//GEN-LAST:event_IconTrabajadorMouseClicked

    private void IconClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconClienteMouseClicked
        TabbedPaneMain.setSelectedIndex(2);
    }//GEN-LAST:event_IconClienteMouseClicked

    private void txtcerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcerrarsesionMouseClicked
        login form= new login();
            form.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_txtcerrarsesionMouseClicked

    private void btnCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarroMouseClicked
        TabbedPaneMain.setSelectedIndex(0);
    }//GEN-LAST:event_btnCarroMouseClicked

    private void btntrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntrabajadorMouseClicked
        TabbedPaneMain.setSelectedIndex(1);        
    }//GEN-LAST:event_btntrabajadorMouseClicked

    private void btnclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclienteMouseClicked
        TabbedPaneMain.setSelectedIndex(2);
    }//GEN-LAST:event_btnclienteMouseClicked
        
    private void btnfacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfacturaMouseClicked
        TabbedPaneMain.setSelectedIndex(5);
    }//GEN-LAST:event_btnfacturaMouseClicked

    private void IconPlantillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconPlantillaMouseClicked
        TabbedPaneMain.setSelectedIndex(3);
    }//GEN-LAST:event_IconPlantillaMouseClicked

    private void btnPlantillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlantillaMouseClicked
        TabbedPaneMain.setSelectedIndex(3);
    }//GEN-LAST:event_btnPlantillaMouseClicked

    
    private void btnproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproductoMouseClicked
        TabbedPaneMain.setSelectedIndex(4);
    }//GEN-LAST:event_btnproductoMouseClicked

    private void PanelProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelProductoMouseClicked
        
    }//GEN-LAST:event_PanelProductoMouseClicked

    private void btncerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarsesionMouseClicked
        login form= new login();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncerrarsesionMouseClicked

    private void txtplavehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplavehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplavehiculoActionPerformed

    private void txtmodvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodvehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmodvehiculoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        objcrud.insertarVehiculos(txtplavehiculo.getText(), txttipvehiculo.getText(), txtmodvehiculo.getText(), txtcolvehiculo.getText(), txtcedcliente.getText(),
                txtobsvehiculo.getText(), txtcedcliente.getText());
    }//GEN-LAST:event_jButton1MouseClicked

    private void txtsulempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsulempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsulempleadoActionPerformed

    private void txtcedempleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedempleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedempleado1ActionPerformed

    private void txtapeempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapeempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapeempleadoActionPerformed

    private void txtdirempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdirempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdirempleadoActionPerformed

    private void txttelempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelempleadoActionPerformed

    private void txtmailempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailempleadoActionPerformed

    private void txtciuempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtciuempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtciuempleadoActionPerformed

    private void txtfecempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfecempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfecempleadoActionPerformed

    private void txtingempleado7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtingempleado7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtingempleado7ActionPerformed

    private void txtespempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtespempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtespempleadoActionPerformed

    private void btnregistrarempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrarempleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistrarempleadoMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {  
        
    }                                       
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void txtnomproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomproductoActionPerformed

    private void txtstoproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstoproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstoproductoActionPerformed

    private void txtfecproducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfecproducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfecproducto1ActionPerformed

    private void txtcodproducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodproducto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodproducto2ActionPerformed

    private void txtcomproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcomproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomproductoActionPerformed

    private void txtvenproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvenproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvenproductoActionPerformed

    private void txtsalplanilla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalplanilla1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalplanilla1ActionPerformed

    private void btnregempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregempleadoActionPerformed

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGr0undlbl;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel IconCarro;
    private javax.swing.JLabel IconCliente;
    private javax.swing.JLabel IconPlantilla;
    private javax.swing.JLabel IconTrabajador;
    private javax.swing.JLabel Iconfactura;
    private javax.swing.JPanel PanelCarros;
    private javax.swing.JPanel PanelClientes;
    private javax.swing.JPanel PanelEmpleados;
    private javax.swing.JPanel PanelFactura;
    private javax.swing.JPanel PanelPlanilla;
    private javax.swing.JPanel PanelProducto;
    private javax.swing.JPanel PanelSorteo;
    private javax.swing.JTabbedPane TabbedPaneMain;
    private javax.swing.JPanel btnCarro;
    private javax.swing.JPanel btnPlantilla;
    private javax.swing.JPanel btncerrarsesion;
    private javax.swing.JPanel btncliente;
    private javax.swing.JPanel btnfactura;
    private javax.swing.JPanel btnproducto;
    private javax.swing.JButton btnregempleado;
    private javax.swing.JPanel btntrabajador;
    private javax.swing.JComboBox<String> cbxcatproducto;
    private javax.swing.JComboBox<String> cmbtiopvehicul;
    private javax.swing.JLabel fondopiratacoche;
    private javax.swing.JLabel iconproducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbapeempleado;
    private javax.swing.JLabel lbcatproducto;
    private javax.swing.JLabel lbcedempleado;
    private javax.swing.JLabel lbcodproducto;
    private javax.swing.JLabel lbdirempleado;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbfecproducto;
    private javax.swing.JLabel lbingplanilla;
    private javax.swing.JLabel lblciuempleado;
    private javax.swing.JLabel lblcoche;
    private javax.swing.JLabel lblcoche1;
    private javax.swing.JLabel lblcoche2;
    private javax.swing.JLabel lblcoche3;
    private javax.swing.JLabel lblcoche4;
    private javax.swing.JLabel lblcoche5;
    private javax.swing.JLabel lblcoche6;
    private javax.swing.JLabel lblcomproducto;
    private javax.swing.JLabel lblnomcliplanilla;
    private javax.swing.JLabel lblregistrarcoches;
    private javax.swing.JLabel lbnomempleado;
    private javax.swing.JLabel lbnomproducto;
    private javax.swing.JLabel lbsalplanilla;
    private javax.swing.JLabel lbstock;
    private javax.swing.JLabel lbtelempleado;
    private javax.swing.JLabel lbtipvehplanilla;
    private javax.swing.JLabel lbvenproducto;
    private javax.swing.JTextField txtapeempleado;
    private javax.swing.JTextField txtcedcliente;
    private javax.swing.JTextField txtcedempleado1;
    private javax.swing.JLabel txtcerrarsesion;
    private javax.swing.JTextField txtciuempleado;
    private javax.swing.JTextField txtcodproducto2;
    private javax.swing.JTextField txtcolvehiculo;
    private javax.swing.JTextField txtcomproducto;
    private javax.swing.JTextArea txtdesplanilla;
    private javax.swing.JTextField txtdirempleado;
    private javax.swing.JTextArea txtempleadoslist;
    private javax.swing.JTextField txtespempleado;
    private javax.swing.JTextField txtfecempleado;
    private javax.swing.JTextField txtfecproducto1;
    private javax.swing.JTextField txtingempleado7;
    private javax.swing.JTextField txtingplanilla;
    private javax.swing.JTextField txtmailempleado;
    private javax.swing.JTextField txtmarvehiculo;
    private javax.swing.JTextField txtmodvehiculo;
    private javax.swing.JTextField txtnomcliplanilla;
    private javax.swing.JTextField txtnomempleado;
    private javax.swing.JTextField txtnomproducto;
    private javax.swing.JTextArea txtobsplanilla;
    private javax.swing.JTextArea txtobsvehiculo;
    private javax.swing.JTextField txtplavehiculo;
    private javax.swing.JTextField txtplavehplanilla;
    private javax.swing.JTextField txtsalplanilla;
    private javax.swing.JTextField txtsalplanilla1;
    private javax.swing.JTextField txtstoproducto;
    private javax.swing.JTextField txtsulempleado;
    private javax.swing.JTextField txttelempleado;
    private javax.swing.JTextField txttipvehiculo;
    private javax.swing.JTextField txtvenproducto;
    // End of variables declaration//GEN-END:variables

}
